name: Keep App Alive

on:
  schedule:
    # Ogni 12 minuti (evita cold start di 15 min)
    - cron: '*/12 * * * *'  # Ogni 12 minuti: 00, 12, 24, 36, 48
  workflow_dispatch: # Permette di eseguire manualmente

jobs:
  ping:
    runs-on: ubuntu-latest
    
    steps:
    - name: Ping Spring Boot App
      run: |
        echo "Pinging app at $(date)"
        curl -f https://tesi-app-backend.onrender.com/api/v1/keep-alive/health || exit 1
        echo "App is alive!"
        
    - name: Ping Alternative Endpoint
      run: |
        echo "Pinging backup endpoint"
        curl -f https://tesi-app-backend.onrender.com/api/v1/keep-alive/ping || exit 1
        echo "Backup ping successful!"

    - name: Wait between requests
      run: sleep 5